# CodeRabbit Configuration
# 3-File Pattern 컨텍스트를 활용한 프로젝트 특화 리뷰 실험
#
# 중요: 이 파일은 반드시 레포 루트에 위치해야 CodeRabbit이 인식합니다.
# path_instructions의 경로는 레포 루트 기준입니다.

language: "ko"

tone_instructions: "모든 리뷰 코멘트를 반드시 한국어로 작성하세요. 프로젝트의 의도적 기술 결정을 존중하되, 결정 근거와 맞지 않는 코드가 있으면 지적하세요."

reviews:
  profile: "assertive"
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbit"
  review_status: true
  auto_review:
    enabled: true
    drafts: false

  # path_instructions 제거: knowledge_base.code_guidelines만으로 컨텍스트가 전달되는지 테스트

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
  code_guidelines:
    enabled: true
    filePatterns:
      - "20260218-3files/CLAUDE.md"
      - "20260218-3files/.claude/docs/**/*.md"
